FROM busybox

<%= snippet('labels', binding) -%>

<%= snippet('container-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

ENTRYPOINT ["/tini", "--", "/container-entrypoint.sh"]
CMD [ "init-loop" ]
